- name: Installing PHP
  yum:
    name: 
    - php
    - php-mysql
    state: installed

- name: Copying your php file in the /var/www/html
  copy:
    src: /etc/ansible/index.php
    dest: /var/www/html/index.php
  notify: restart_apache
