- name: start_apache
  service: 
    name: httpd
    state: started
#- name: start_apache
#  service:
#    name: mariadb
#    state: started

- name: restart_apache
  service:
    name: httpd
    state: restarted
